### ISSUE TITLE
Traceback with HASSIO and UNO-DM-4.6-TL-PLUS

### ISSUE THREAD

**Issue by Claudio1L** [alexdelprete/ha-abb-powerone-pvi-sunspec#23]
After months without issues (UNO-DM-4.6-TL-PLUS), today after HA reboot started the following traceback, with all entities unavaileable:

Logger: homeassistant.components.sensor
Source: custom_components/abb_powerone_pvi_sunspec/__init__.py:293
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 08:21:20 (1 occurrences)
Last logged: 08:21:20
Error while setting up abb_powerone_pvi_sunspec platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/abb_powerone_pvi_sunspec/sensor.py", line 21, in async_setup_entry
    hub.read_modbus_data_realtime()
  File "/config/custom_components/abb_powerone_pvi_sunspec/__init__.py", line 293, in read_modbus_data_realtime
    self.data["invtype"] = INVERTER_TYPE[invtype]
KeyError: 102

Also tested with a previous VM snapshot. Same traceback.

Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Anything to check?

**Comment by Claudio1L** [comment]
after removing and readding the integration, the device disappeared. 
![immagine](https://user-images.githubusercontent.com/97904190/176367826-eb3ebb68-1875-4839-866f-27e125639630.png)

**Comment by Claudio1L** [comment]
After a reboot of the inverter the issue is gone. Let's see what's happening.
