### ISSUE TITLE
Error installing integration

### ISSUE THREAD

**Issue by Polvere79** [alexdelprete/ha-abb-powerone-pvi-sunspec#36]
Hi, 

I've been trying installing this integration, but I always get the following error:
```
Errore
Impossibile caricare il flusso di configurazione: {"message":"Invalid handler specified"}
```

The log shows the following:
```
2022-10-24 18:12:06.919 INFO (SyncWorker_7) [homeassistant.util.package] Attempting install of pymodbus==3.0.0
2022-10-24 18:12:15.199 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.abb_powerone_pvi_sunspec.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/abb_powerone_pvi_sunspec/__init__.py", line 15, in <module>
    from pymodbus.client import ModbusTcpClient
  File "/srv/homeassistant/lib/python3.10/site-packages/pymodbus/client/__init__.py", line 5, in <module>
    from pymodbus.client.serial import AsyncModbusSerialClient, ModbusSerialClient
  File "/srv/homeassistant/lib/python3.10/site-packages/pymodbus/client/serial.py", line 10, in <module>
    from pymodbus.client.base import ModbusBaseClient, ModbusClientProtocol
  File "/srv/homeassistant/lib/python3.10/site-packages/pymodbus/client/base.py", line 9, in <module>
    from pymodbus.client.mixin import ModbusClientMixin
  File "/srv/homeassistant/lib/python3.10/site-packages/pymodbus/client/mixin.py", line 19, in <module>
    class ModbusClientMixin:  # pylint: disable=too-many-public-methods
  File "/srv/homeassistant/lib/python3.10/site-packages/pymodbus/client/mixin.py", line 56, in ModbusClientMixin
    count: int = Defaults.Count,
AttributeError: type object 'Defaults' has no attribute 'Count'
2022-10-24 18:12:15.211 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration abb_powerone_pvi_sunspec: Exception importing custom_components.abb_powerone_pvi_sunspec.config_flow
```

Could you please help me with this?

Thanks

**Comment by alexdelprete** [comment]
I just noticed you opened the issue, as you can see from the log:

```
2022-10-24 18:12:06.919 INFO (SyncWorker_7) [homeassistant.util.package] Attempting install of pymodbus==3.0.0
2022-10-24 18:12:15.199 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.abb_powerone_pvi_sunspec.config_flow
```

the problem is when HA tries to install pymodbus 3.0.0. Probably it has an issue installing it, and that's a requirement for the component, without it it won't work.
