### ISSUE TITLE
Inverter non connesso

### ISSUE THREAD

**Issue by naamah75** [alexdelprete/ha-abb-powerone-pvi-sunspec#96]
Salve, l'integrazione all'inverter funzionava correttamente fino alla versione 2023.11.2 (mi pare... cioè fino a due versione fa rispetto alla 2023.12.0)... ho provato a ricaricare l'integrazione più volte, riavviare Home Assisitant e alla fine anche cancellare l'integrazione e reinserirla, ma niente.
Sui registri ho il seguente errore 

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 11:09:14 (1 occurrences)
Last logged: 11:09:14

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 90, in async_step_user
    uid = await self.test_connection(name, host, port, slave_id, base_addr, scan_interval)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 65, in test_connection
    self.hub_data = await self.hub.async_get_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 185, in async_get_data
    self.read_sunspec_modbus_model_1()
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 221, in read_sunspec_modbus_model_1
    read_model_1_data.registers, byteorder=Endian.BIG
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModbusIOException' object has no attribute 'registers'

```

Le seguenti sono le informazioni sulla versione:
Core 2023.12.0
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231206.0

**Comment by alexdelprete** [comment]
Non uso aiohttp, quindi non ho idea di cosa rappresenti quell'errore.

Abilita il debug dell'integrazione, ricaricala o riavvia HA, poi disabilita il debug, ti dovrebbe scaricare il log. Postalo qui e vediamo un attimo che ti sta succedendo...

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/1d016e4b-d8f4-402b-aed0-49f80485b2bd)

**Comment by naamah75** [comment]
Scusami, non mi sono spiegato bene, l'installazione è scaricata da HACS ma non più installata.

**Comment by alexdelprete** [comment]
Avevi scritto:  "l'installazione è scaricata da HACS **_ma non più installata_**"

Comunque, se è sul config flow il problema, ci sono i log di HA, quelli completi, cerca la stringa ABB e riportami eventuali errori oppure passami tutto il file.

**Comment by alexdelprete** [comment]
Bastava filtrare con stringa ABB ed estrapolare queste righe:

```
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 90, in async_step_user
    uid = await self.test_connection(name, host, port, slave_id, base_addr, scan_interval)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 65, in test_connection
    self.hub_data = await self.hub.async_get_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 185, in async_get_data
    self.read_sunspec_modbus_model_1()
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 221, in read_sunspec_modbus_model_1
    read_model_1_data.registers, byteorder=Endian.BIG
```

Ma tutto parte dall'errore originale:

```
2023-12-20 14:55:53.616 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
```

E riguarda tutte le integrazioni, non solo questa. Hai una marea di errori in generale sul log.

Mi spiace ma non so come aiutarti. Posso solo dirti di fare un installazione pulita di HA. Un log del genere è sintomo di problemi di base.

Poi se vuoi, puoi installare la versione dell'integrazione che dicevi funzionasse, la 2023.11.2, per verificare. Secondo me non ti funziona neanche quella, anche perché quella parte del codice non è cambiata.

**Comment by MatteGary** [comment]
Ciao,
Ho avuto anche io un problema simile, e non appena l’integrazione con l’inverter ha smesso di funzionare tutto il sistema è diventato instabile e lento.
Ora ho disabilitato l’integrazione e devo fare alcune prove per verificare i miei dubbi.

che tipo di log posso raccogliere per capire se il problema è effettivamente in questa integrazione, e come aiutarti eventualmente a risolverlo?

**Comment by naamah75** [comment]
> Ciao, Ho avuto anche io un problema simile, e non appena l’integrazione con l’inverter ha smesso di funzionare tutto il sistema è diventato instabile e lento. Ora ho disabilitato l’integrazione e devo fare alcune prove per verificare i miei dubbi.
> 
> che tipo di log posso raccogliere per capire se il problema è effettivamente in questa integrazione, e come aiutarti eventualmente a risolverlo?

Io ho risolto rispolverando un flusso Node-Red che usavo prima di questa integrazione, se vuoi ti passo i dettagli

**Comment by MatteGary** [comment]
Piccolo aggiornamento: con la configurazione cancellata (quindi non più presente in lista ma ancora installata tramite HACS) i problemi ad HA sono spariti.

Poco fa ho provato ad aggiungere di nuovo l’inverter, ma la schermata di configurazione è rimasta con la spinning wheel e tutto il sistema si è freezato.
Dopo un minuto si è ripreso, e c’erano vari errori su supervisor e api call.
Questo che allego qua sotto è l’errore strettamente legato alla configurazione del l’inverter


```

Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 13:19:58 (1 occurrences)
Last logged: 13:19:58

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 90, in async_step_user
    uid = await self.test_connection(name, host, port, slave_id, base_addr, scan_interval)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/config_flow.py", line 65, in test_connection
    self.hub_data = await self.hub.async_get_data()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 185, in async_get_data
    self.read_sunspec_modbus_model_1()
  File "/config/custom_components/abb_powerone_pvi_sunspec/api.py", line 221, in read_sunspec_modbus_model_1
    read_model_1_data.registers, byteorder=Endian.BIG
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModbusIOException' object has no attribute 'registers'

```

**Comment by MatteGary** [comment]
Ciao, non sto usando altre componenti che usano pymodbus, prima usavo rest per recuperare i parametri dall’inverter.

Per HA ho un mini pc con HA OS, e le performance non sono un problema.
